4teamwork/ftw.contacts

- ftw/contacts/configure.zcml
- ftw/contacts/resources.zcml
- ftw/contacts/resources/contacts.scss
Declare font-awesome type icons when ftw.theming is installed.
> add ftw.theming support: declare fa icons.

- ftw/contacts/simplelayout/memberblock.pt
- ftw/contacts/tests/test_member_block_view.py
It has been decided that the caption is not needed anymore because the name of the contact is already displayed next to the image.
> Remove image caption.

- ftw/contacts/browser/contactfolder.py
- ftw/contacts/tests/test_contact_folder_reload.py
@jone 
We have a contactdirectory:
If we replace the special chars with a space, we'll not be able to find contacts if the user inserts a special char:
I changed the _cleanup_query to replace the special chars with a empty string. Now it's possible to find them:
> Replace special chars in search-query with empty string

- development.cfg
- ftw/contacts/profiles/default/metadata.xml
- ftw/contacts/simplelayout/configure.zcml
- ftw/contacts/simplelayout/contents/memberblock.py
- ftw/contacts/simplelayout/interfaces.py
- ftw/contacts/simplelayout/profiles/default/metadata.xml
- ftw/contacts/simplelayout/profiles/default/registry.xml
- ftw/contacts/simplelayout/upgrades/20150924163411_add_member_registry_for_source_path/registry.xml
- ftw/contacts/simplelayout/upgrades/20150924163411_add_member_registry_for_source_path/upgrade.py
- ftw/contacts/tests/test_address_obj_path_source_binder.py
- setup.py
@maethu 
Add registry property to set the sourcepath for member-blocks.
If you add a memberblock, you can add a source-contact. 
The default path source is the plone siteroot:
You can set the path to a certain plone object, i.e. our contactdirectory:
And now, if you try to reference a contact through a memberblock, the path source is our contac-directory:
> Es 700 path source for members

- ftw/contacts/tests/test_adapter_memberaccessor.py
The test uses the firstname as test case, but the firstname is not part
of the address and cannot be changed in the member block and therefore
is not the right attribute.
It is changed to the `address` attribute.
This fixes test failures which are happening since the builder no longer
blindly sets attributes:
https://github.com/4teamwork/ftw.builder/pull/45
> fix member adapter accessor test.

- ftw/contacts/locales/de/LC_MESSAGES/ftw.contacts.po
- ftw/contacts/resources/contacts.scss
- ftw/contacts/resources/ftw.contacts.css
@bierik 
If the font-size is bigger than in default-plone, we have some unnecessary linebreaks.
I adjust the styling to avoid this.
Before
---------
After
------
> Add contactfolder styling to use the given space

- docs/HISTORY.txt
- ftw/contacts/browser/contact_summary.pt
Adjust contact_summary template to display the title in the details only if it is different than the organization name.
This happens if you fill only an organization name without a first and last name.
Before:
----------
After:
-------
> Adjust contact_summary template.

- docs/HISTORY.txt
- ftw/contacts/browser/configure.zcml
- ftw/contacts/resources/contactfolder_listing.js
- ftw/contacts/tests/test_contact_folder_reload.py
The reload view is sometimes used by another package.
To be unique, I change it to the more specific name ``reload_contacts``.
> Change ``reload`` view name to more specific name ``reload_contacts``.

- docs/HISTORY.txt
- ftw/contacts/browser/contact.py
- ftw/contacts/browser/templates/contact.pt
- ftw/contacts/geo/configure.zcml
- setup.py
The map will be rendered directly in the contact.pt now.
The default collective.geo.kml package includes the map either into
the abovecontentbody or belowcontentbody viewlet manager. This will produce
several issues:
1. It's not easy to customize the layout with the map. I.e. if you want to
move the map to the right site instead the contact image you will ran into
problems.
2. The viewlets will be disabled through ajax requests (ajax_load). So if you want
to display the contact with the map in an ajax-generated overlay, the map will
not be displayed.
It's possible to render the map with the provided macros (openlayer and map-widget).
The problem here is, that the viewlets will be still present and it's not possible
to deactivate a specific viewlet only for one type.
Overriding the viewlet …
> Disable rendering map widget through the viewlet.

- docs/HISTORY.txt
- ftw/contacts/geo/configure.zcml
The profilehook name was false.
On newly installed instances with ftw.contacts.geo integration, the hook haven't been registered.
> Fix broken profilehook name

- docs/HISTORY.txt
- setup.py
This makes the "ftw.openlayerhotfix" obsolete.
> Install a newer version of "collective.geo.openlayers".

- docs/HISTORY.txt
- ftw/contacts/browser/contact.py
- ftw/contacts/browser/templates/contact.pt
- ftw/contacts/testing.py
- ftw/contacts/tests/builders.py
- ftw/contacts/tests/test_contact_type.py
The membership links on the contact detail view now point to the container containing the memberblock and not to the memberblock itself.
> Let the membership links point to the container of the memberblock.

- docs/HISTORY.txt
- ftw/contacts/tests/test_utils_get_backreferences.py
- ftw/contacts/utils.py
Before only the "Manager" role was able to see referenced members.
> Fix permission check in utls.py (get_backreferences). It's "View" not "zope2.View"

- docs/HISTORY.txt
- ftw/contacts/simplelayout/templates/memberblock.pt
This is achieved by rendering less line breaks in the member block template if there is no content to follow the line break.
> Reduce space between member block and following block.

- docs/HISTORY.txt
- ftw/contacts/browser/contact.py
- ftw/contacts/tests/test_contact_type.py
The memberships must be sorted by the title of their container because the memberships are in fact member blocks inside content pages. Most member blocks do not even have a title, so we cannot sort by the title of the block itself.
This is a follow-up of https://github.com/4teamwork/ftw.contacts/pull/43
> Improve sorting of memberships of a contact.

- docs/HISTORY.txt
- ftw/contacts/resources/scss/contacts.scss
Accidentally the loadmore button is using the `default` color.
Because the loadmore button is visible for anonymous users it
should be displayed in the primary color.
> Use primary color for load more button.

- docs/HISTORY.txt
- ftw/contacts/profiles/default/types/Plone_Site.xml
When `ftw.contacts` is installed the MemberBlock can now be added to plone site per default.
We don't want an upgrade step for this because we don't want to change how existing deployments handle the MemberBlock.
> Make MemberBlock addable on plone site

- docs/HISTORY.txt
- ftw/contacts/resources/contactfolder_listing.js
- ftw/contacts/resources/scss/summary.scss
See https://github.com/4teamwork/edubsch.policy/issues/15
The current implementation relies on the offsets of the contacts in the first row
to determine the amount of items in one row.
> Fix javascript calculated row distribution.

- docs/HISTORY.txt
- ftw/contacts/browser/templates/contact_summary.pt
- ftw/contacts/resources/contactfolder_listing.js
- ftw/contacts/resources/scss/summary.scss
See https://github.com/4teamwork/nidau.web/issues/17
See https://github.com/4teamwork/nidau.web/issues/18
A link without an image would look like this:
> Fix row distribution for n rows

- docs/HISTORY.txt
- ftw/contacts/browser/templates/contact.pt
There is no need to get the contact's relationships if they should not be rendered at all.
> Improve contact detail view.

- docs/HISTORY.txt
- ftw/contacts/simplelayout/member.py
- ftw/contacts/tests/test_member_block_view.py
The block used to fail if it did not have a reference to a contact.
> Make memberblock more robust

- docs/HISTORY.txt
- ftw/contacts/simplelayout/templates/memberblock.pt
See discussion in https://github.com/4teamwork/nidau.web/issues/35
> Add label to email field in memberblock for consistency reasons.

- docs/HISTORY.txt
- ftw/contacts/browser/templates/contact.pt
Adds a comma between address and city in the contact template to visually separate the two.
Before:
After:
> Add comma to separate address and city in contact view

- ftw/contacts/sync/sync.py
Follow up to: https://github.com/4teamwork/ftw.contacts/pull/62
This change was already deployed on the test system, but wasn't synced. 🙈 
The check on the dn (not always the dn, but the configured id) is necessary because if the filter is not perfect, group objects are picked up by the sync. Those don't have the dn (id).
Then some encoding stuff, because dn can apparently contain umlauts.
> Fix contact sync for umlaut id's and group objects.

- test-plone-4.3.x.cfg
Pin some package to a release compatible with Plone 4. Newer releases are for Plone 5, breaking buildout.
Closes https://github.com/4teamwork/ftw.contacts/issues/68
> Fix buildout.

- docs/HISTORY.txt
- ftw/contacts/resources/contactfolder_listing.js
A strange race condition caused the "show more" button to be hidden even if there were more contacts to be shown.
We prevent this by aborting pending AJAX requests to the "@@reload_contacts" view.
> Fix a bug where the "show more" button was hidden erroneously.

- docs/HISTORY.txt
- ftw/contacts/sync/sync.py
`ObjectCreatedEvent` is already fired in `plone.dexterity.utils.createContent()`, so we don't need to fire it again. But the real problem here is `plone.app.contentrules` not listening on `ObjectCreatedEvent` but rather `ObjectAddedEvent`.
> Fire different event in the sync script.

- docs/HISTORY.txt
- ftw/contacts/sync/sync.py
This is required if we want to execute workflow actions through content rules.
> Setup security in the in the sync script.

- docs/HISTORY.txt
- ftw/contacts/simplelayout/templates/member.pt
The script anyway did not help much to protext from any spam:
```
def escape(s):
if s is not None:
s = s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')
return s
mailaddress = escape(mailaddress)
mailname = escape(mailname)
cssclass = escape(cssclass)
cssid = escape(cssid)
email = mailaddress.replace('@', '&#0064;').replace(':', '&#0058;')
if mailname is None:
mailname = email
if cssid is None:
cssid = ''
else:
cssid = ' id="%s"' % cssid
if cssclass is None:
cssclass = ''
else:
cssclass = ' class="%s"' % cssclass
return '<a href="&#0109;ailto&#0058;' + email + '"' + cssclass \
+ cssid + '>' + mailname + '</a>'
```
> Remove usage of spamProtect script, since it's no longer available in plone 5.

- docs/HISTORY.txt
- ftw/contacts/__init__.py
- ftw/contacts/browser/configure.zcml
- ftw/contacts/browser/contact.py
- ftw/contacts/contents/contact.py
- ftw/contacts/locales/de/LC_MESSAGES/ftw.contacts.po
- ftw/contacts/locales/fr/LC_MESSAGES/ftw.contacts.po
- ftw/contacts/locales/ftw.contacts.pot
- ftw/contacts/locales/it/LC_MESSAGES/ftw.contacts.po
- ftw/contacts/simplelayout/templates/member.pt
Resolves issue in Plone 5 where rename popup doesn't work.
Resolves https://github.com/4teamwork/izug.organisation/issues/1895
This also hides the Title field in the Plone 5 object_rename form to save user confusion.
This _doesn't_ hide the Title field for the popup in folder_contents - that is much more involved (and doesn't seem to be used by our customer)
> Fix contact renames

- docs/HISTORY.txt
- ftw/contacts/sync/sync.py
An LDAP-sync had values which were just strings with whitespaces. And we generally don't want values purely existing out of newlines/whitespaces because they are true-ish in python but are basically empty, it only generates problems. And additionally, it doesn't make sense to have trailing whitespaces/newlines either.
> Strip ldap synced values

- test-plone-5.1.x.cfg
If geopy was unpinned buildout would get the most recent version of geopy which is not Python 2.7 compatible anymore.
> Pin geopy to Python2 compatible version.

- docs/HISTORY.txt
- ftw/contacts/simplelayout/memberblock.py
- ftw/contacts/tests/test_member_block_view.py
We disabled dizo for memberblocks so that it does not throw a ecoding error in tests. But it had the side effect to break the whole content page it was in. To fix this we just rewrite the tests to not get in the situation where we get the encoding error and do not disable diazo.
> Fix broken contentpage with memberblock

- docs/HISTORY.txt
- ftw/contacts/configure.zcml
- ftw/contacts/indexers.py
This fixes displaying the contact icon - otherwise i tries to render a bad mimetype icon on search pages / livesearch.
> Always return False for getIcon index on contacts.
