4teamwork/ftw.contacts

ftw/contacts/resources/ftw.contacts.css
Fixed through https://github.com/4teamwork/ftw.simplelayout/pull/237
=> Overlays not stacked correctly.

ftw/contacts/browser/contactfolder.py, ftw/contacts/tests/test_contact_folder_reload.py
@jone 
Fixed show more button:
If you have several contacts and filter them through a click on the letter, the max_contacts var should be the amount of filtered contacts instead of the amount of all contacts.
=> Es fix load more button

ftw/contacts/browser/contactfolder.py, ftw/contacts/resources/ftw.contacts.css, ftw/contacts/tests/test_contact_folder_reload.py
@jone :top: of https://github.com/4teamwork/ftw.contacts/pull/7
Update letter css:
Old
===
New
===
=> Es update letter css

ftw/contacts/browser/letters.pt, ftw/contacts/profiles/default/cssregistry.xml, ftw/contacts/resources/contactfolder_listing.js, ftw/contacts/resources/contacts.scss, ftw/contacts/resources/ftw.contacts.css, ftw/contacts/tests/test_contact_folder_reload.py, ftw/contacts/utils.py
@jone 
- Add scss for integration into ftw.theming
- Some adjustments for the integration (buttons have a .active class instead .current)
:top: of #8 
See PR: https://github.com/4teamwork/ftw.theming/pull/16
=> Add scss for ftw.theming

ftw/contacts/browser/contactfolder.py, ftw/contacts/browser/letters.pt, ftw/contacts/profiles/default/cssregistry.xml, ftw/contacts/resources/contactfolder_listing.js, ftw/contacts/resources/contacts.scss, ftw/contacts/resources/ftw.contacts.css, ftw/contacts/tests/test_contact_folder_reload.py, ftw/contacts/utils.py
@jone 
- Add delay if searching for a contact to reduce the requests
Before: if I search for "James" it sends requests each time i do a keyup...
After: If I search for "James" it searches with a delay of 200ms...
=> Es add keyup delay

ftw/contacts/resources/contacts.scss
Fixes https://github.com/4teamwork/bern.web/issues/796
=> Searchtext is not middle aligned.

ftw/contacts/resources/contactfolder_listing.js
@bierik 
Enter Key deactivated for accessibility.
=> Deactivate enter key on search field for accessibility

ftw/contacts/resources/contacts.scss
Adjust css for letters for ftw.theming:
Before:
After:
=> Adjust css for contactfolder

docs/HISTORY.txt, ftw/contacts/resources/contactfolder_listing.js
For better integration into other package, we need to trigger an event if the contacts are reloaded.
=> Trigger event if contacts are reloaded.

ftw/contacts/locales/de/LC_MESSAGES/ftw.contacts.po, ftw/contacts/locales/fr/LC_MESSAGES/ftw.contacts.po, ftw/contacts/locales/it/LC_MESSAGES/ftw.contacts.po
Add basic italien and french translation.
=> Add italien and french translation

ftw/contacts/resources/scss/search.scss
See https://github.com/4teamwork/plonetheme.blueberry/pull/69
=> Move these styles from plonetheme.blueberry

docs/HISTORY.txt, ftw/contacts/configure.zcml, ftw/contacts/contents/contact.py, ftw/contacts/interfaces.py, ftw/contacts/profiles/default/registry.xml, ftw/contacts/sync/command.py, ftw/contacts/sync/configure.zcml, ftw/contacts/sync/ldap.py, ftw/contacts/sync/mapper.py, ftw/contacts/sync/sync.py, ftw/contacts/tests/__init__.py, ftw/contacts/tests/assets/contact.ldif, ftw/contacts/tests/assets/contacts.ldif, ftw/contacts/tests/test_sync.py, ftw/contacts/upgrades/20160725150055_add_ldap_registry/registry.xml, ftw/contacts/upgrades/20160725150055_add_ldap_registry/upgrade.py, setup.py
*  `Contact` got a new hidden field `ldap_dn` to save the DN.
*  Added registry entry to configure contacts directory and ldap plugin id
*  Moved sync logic from `egov.contactdiretory` and modified it to work (only) with dexterity content.
=> Move syncing from egov.contactdirectory and make it dx ready.

README.rst, docs/HISTORY.txt, ftw/contacts/simplelayout/profiles/default/metadata.xml
The extra is an addon of ftw.simplelayout and should not install it.
=> Remove metadata.xml-dependencie to ftw.simplelayout in the simplelayout extra profile.

ftw/contacts/resources/contactfolder_listing.js, ftw/contacts/resources/scss/summary.scss
this sets the height of all items to the same height as the highest element this way the rows should always be the same.
Before:
After:
=> set rowheight to highest item

docs/HISTORY.txt, ftw/contacts/resources/contactfolder_listing.js
Sorting numeric values was not working as expected.
=> Fix contacts summary view.

bootstrap.py, docs/HISTORY.txt, ftw/contacts/sync/sync.py
Until now we were not able to store data in schemas provided through behaviors during the synchronisation with some directory service.
=> Sync additional behaviors

test-plone-4.3.x.cfg
Currently the `master` is failing: https://ci.4teamwork.ch/builds/228227/tasks/374816
=> Fix buildout for Plone 4.

ftw/contacts/tests/__init__.py, ftw/contacts/tests/test_adapter_locationstring.py, ftw/contacts/tests/test_adapter_memberaccessor.py, ftw/contacts/tests/test_contact_folder_reload.py, ftw/contacts/tests/test_contact_type.py, ftw/contacts/tests/test_contactfolder_type.py, ftw/contacts/tests/test_member_block_view.py, ftw/contacts/tests/test_utils_alphabetical_letters.py, ftw/contacts/tests/test_utils_encode.py, ftw/contacts/tests/test_utils_get_backreferences.py, ftw/contacts/tests/test_utils_get_contact_title.py, ftw/contacts/tests/test_utils_get_organization.py, ftw/contacts/tests/test_utils_make_sortable.py, ftw/contacts/tests/test_utils_normalize_first_letter.py, ftw/contacts/tests/test_utils_safe_html.py, ftw/contacts/tests/test_vcard_export.py, ftw/contacts/tests/test_zipexport.py, setup.py
Use unittest instead of unittest2.
=> Use unittest instead of unittest2.

docs/HISTORY.txt, ftw/contacts/locales/de/LC_MESSAGES/plone.po, ftw/contacts/locales/fr/LC_MESSAGES/plone.po, ftw/contacts/locales/it/LC_MESSAGES/plone.po, ftw/contacts/locales/plone.pot
part of https://github.com/4teamwork/izug.organisation/issues/1745
=> Add ftw.contacts portal_types translations to plone domain.

README.rst, docs/HISTORY.txt, setup.py
Not sure if Plone 4.2 support should be listed?  It's in setup.py but not in README.
=> Brush up English in README and clarify Plone 5.1 support

README.rst, docs/HISTORY.txt, ftw/contacts/sync/ldap.py, ftw/contacts/sync/sync.py
Scope can be set to: ``SCOPE_BASE``, ``SCOPE_ONELEVEL``, ``SCOPE_SUBTREE`` or ``SCOPE_SUBORDINATE``.
=> Add ldap scope attribute support

docs/HISTORY.txt, ftw/contacts/profiles/default_plone5/types/ftw.contacts.Contact.xml, ftw/contacts/profiles/default_plone5/types/ftw.contacts.ContactFolder.xml
I wanted to extend the uninstall profile with the remaining stuff we install but I ran into an error. I'll be doing that on a later occasion then, no time right now.
=> Remove obsolete behaviours

docs/HISTORY.txt, ftw/contacts/simplelayout/upgrades/20200923141935_remove_oboslete_behaviour_in_plone_5/types/ftw.contacts.MemberBlock.xml
=> Fix harming upgrade step from release 1.10.3, which removed all behaviors.
